rem
rem hotel_create.sql - Creates schema objects for the HOTEL practice
rem schema (a fictional Peruvian hotel chain), used for teaching SQL /
rem database management.
rem
rem This script is called from hotel_install.sql and assumes the session's
rem CURRENT_SCHEMA is already set to HOTEL.
rem
rem NOTE FOR INSTRUCTORS: guests.last_name and reservations.channel are
rem deliberately left WITHOUT indexes, so students can decide which index
rem type (B-tree / bitmap) fits each column.
rem --------------------------------------------------------------------------

SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 100
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

Prompt ******  Creating HOTELS table ....

CREATE TABLE hotels
(
  hotel_id      INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  hotel_name    VARCHAR2(100 CHAR) NOT NULL,
  city          VARCHAR2(100 CHAR) NOT NULL,
  address       VARCHAR2(255 CHAR) NOT NULL,
  stars         NUMBER(1,0) NOT NULL,
  phone         VARCHAR2(30 CHAR),
  opened_date   DATE NOT NULL
);

Prompt ******  Creating ROOM_TYPES table ....

CREATE TABLE room_types
(
  room_type_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  type_name      VARCHAR2(50 CHAR) NOT NULL,
  max_guests     NUMBER(2,0) NOT NULL,
  base_rate      NUMBER(8,2) NOT NULL,
  description    VARCHAR2(255 CHAR)
);

Prompt ******  Creating ROOMS table ....

CREATE TABLE rooms
(
  room_id        INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  hotel_id       INTEGER NOT NULL,
  room_type_id   INTEGER NOT NULL,
  room_number    VARCHAR2(10 CHAR) NOT NULL,
  floor          NUMBER(2,0) NOT NULL,
  nightly_rate   NUMBER(8,2) NOT NULL
);

Prompt ******  Creating GUESTS table ....

CREATE TABLE guests
(
  guest_id            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  document_type       VARCHAR2(10 CHAR) NOT NULL,
  document_number     VARCHAR2(20 CHAR) NOT NULL,
  first_name          VARCHAR2(100 CHAR) NOT NULL,
  last_name           VARCHAR2(100 CHAR) NOT NULL,
  country             VARCHAR2(60 CHAR) NOT NULL,
  email_address       VARCHAR2(255 CHAR),
  phone               VARCHAR2(30 CHAR),
  birth_date          DATE,
  registration_date   DATE DEFAULT SYSDATE NOT NULL
);

Prompt ******  Creating EMPLOYEES table ....

CREATE TABLE employees
(
  employee_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  full_name     VARCHAR2(255 CHAR) NOT NULL,
  email_address VARCHAR2(255 CHAR) NOT NULL,
  job_title     VARCHAR2(100 CHAR) NOT NULL,
  hotel_id      INTEGER,
  manager_id    INTEGER,
  hire_date     DATE NOT NULL,
  salary        NUMBER(10,2) NOT NULL
);

Prompt ******  Creating RESERVATIONS table ....

CREATE TABLE reservations
(
  reservation_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  guest_id         INTEGER NOT NULL,
  room_id          INTEGER NOT NULL,
  employee_id      INTEGER,
  booking_date     DATE NOT NULL,
  check_in_date    DATE NOT NULL,
  check_out_date   DATE NOT NULL,
  num_guests       NUMBER(2,0) NOT NULL,
  channel          VARCHAR2(10 CHAR) NOT NULL,
  status           VARCHAR2(12 CHAR) NOT NULL
);

Prompt ******  Creating STAYS table ....

CREATE TABLE stays
(
  stay_id            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  reservation_id     INTEGER NOT NULL,
  actual_check_in    TIMESTAMP NOT NULL,
  actual_check_out   TIMESTAMP NOT NULL,
  nights             NUMBER(3,0) NOT NULL,
  room_charge        NUMBER(10,2) NOT NULL
);

Prompt ******  Creating SERVICES table ....

CREATE TABLE services
(
  service_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  service_name   VARCHAR2(100 CHAR) NOT NULL,
  category       VARCHAR2(20 CHAR) NOT NULL,
  unit_price     NUMBER(8,2) NOT NULL
);

Prompt ******  Creating SERVICE_CHARGES table ....

CREATE TABLE service_charges
(
  charge_id     INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  stay_id       INTEGER NOT NULL,
  service_id    INTEGER NOT NULL,
  charge_date   DATE NOT NULL,
  quantity      NUMBER(3,0) NOT NULL,
  unit_price    NUMBER(8,2) NOT NULL
);

Prompt ******  Creating INVOICES table ....

CREATE TABLE invoices
(
  invoice_id        INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  stay_id           INTEGER NOT NULL,
  invoice_date      DATE NOT NULL,
  invoice_type      VARCHAR2(10 CHAR) NOT NULL,
  payment_method    VARCHAR2(20 CHAR) NOT NULL,
  room_amount       NUMBER(10,2) NOT NULL,
  services_amount   NUMBER(10,2) NOT NULL,
  tax_amount        NUMBER(10,2) NOT NULL,
  total_amount      NUMBER(10,2) NOT NULL
);

rem ********************************************************************
rem Create constraints

Prompt ******  Adding constraints to tables ...

ALTER TABLE hotels ADD CONSTRAINT hotels_pk PRIMARY KEY (hotel_id);
ALTER TABLE hotels ADD CONSTRAINT hotels_name_u UNIQUE (hotel_name);
ALTER TABLE hotels ADD CONSTRAINT hotels_stars_c CHECK ( stars BETWEEN 1 AND 5 );

ALTER TABLE room_types ADD CONSTRAINT room_types_pk PRIMARY KEY (room_type_id);
ALTER TABLE room_types ADD CONSTRAINT room_types_name_u UNIQUE (type_name);

ALTER TABLE rooms ADD CONSTRAINT rooms_pk PRIMARY KEY (room_id);
ALTER TABLE rooms ADD CONSTRAINT rooms_hotel_number_u UNIQUE (hotel_id, room_number);
ALTER TABLE rooms ADD CONSTRAINT rooms_hotel_id_fk
  FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);
ALTER TABLE rooms ADD CONSTRAINT rooms_room_type_id_fk
  FOREIGN KEY (room_type_id) REFERENCES room_types (room_type_id);

ALTER TABLE guests ADD CONSTRAINT guests_pk PRIMARY KEY (guest_id);
ALTER TABLE guests ADD CONSTRAINT guests_document_u UNIQUE (document_type, document_number);
ALTER TABLE guests ADD CONSTRAINT guests_document_type_c
  CHECK ( document_type IN ('DNI','PASSPORT','CE') );

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY (employee_id);
ALTER TABLE employees ADD CONSTRAINT employees_email_u UNIQUE (email_address);
ALTER TABLE employees ADD CONSTRAINT employees_hotel_id_fk
  FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id);
ALTER TABLE employees ADD CONSTRAINT employees_manager_id_fk
  FOREIGN KEY (manager_id) REFERENCES employees (employee_id);

ALTER TABLE reservations ADD CONSTRAINT reservations_pk PRIMARY KEY (reservation_id);
ALTER TABLE reservations ADD CONSTRAINT reservations_guest_id_fk
  FOREIGN KEY (guest_id) REFERENCES guests (guest_id);
ALTER TABLE reservations ADD CONSTRAINT reservations_room_id_fk
  FOREIGN KEY (room_id) REFERENCES rooms (room_id);
ALTER TABLE reservations ADD CONSTRAINT reservations_employee_id_fk
  FOREIGN KEY (employee_id) REFERENCES employees (employee_id);
ALTER TABLE reservations ADD CONSTRAINT reservations_dates_c
  CHECK ( check_out_date > check_in_date );
ALTER TABLE reservations ADD CONSTRAINT reservations_channel_c
  CHECK ( channel IN ('WEB','PHONE','AGENCY') );
ALTER TABLE reservations ADD CONSTRAINT reservations_status_c
  CHECK ( status IN ('CONFIRMED','CHECKED_OUT','CANCELLED','NO_SHOW') );

ALTER TABLE stays ADD CONSTRAINT stays_pk PRIMARY KEY (stay_id);
ALTER TABLE stays ADD CONSTRAINT stays_reservation_id_u UNIQUE (reservation_id);
ALTER TABLE stays ADD CONSTRAINT stays_reservation_id_fk
  FOREIGN KEY (reservation_id) REFERENCES reservations (reservation_id);

ALTER TABLE services ADD CONSTRAINT services_pk PRIMARY KEY (service_id);
ALTER TABLE services ADD CONSTRAINT services_name_u UNIQUE (service_name);
ALTER TABLE services ADD CONSTRAINT services_category_c
  CHECK ( category IN ('FOOD','BAR','SPA','LAUNDRY','TRANSPORT','TOUR') );

ALTER TABLE service_charges ADD CONSTRAINT service_charges_pk PRIMARY KEY (charge_id);
ALTER TABLE service_charges ADD CONSTRAINT service_charges_stay_id_fk
  FOREIGN KEY (stay_id) REFERENCES stays (stay_id);
ALTER TABLE service_charges ADD CONSTRAINT service_charges_service_id_fk
  FOREIGN KEY (service_id) REFERENCES services (service_id);

ALTER TABLE invoices ADD CONSTRAINT invoices_pk PRIMARY KEY (invoice_id);
ALTER TABLE invoices ADD CONSTRAINT invoices_stay_id_u UNIQUE (stay_id);
ALTER TABLE invoices ADD CONSTRAINT invoices_stay_id_fk
  FOREIGN KEY (stay_id) REFERENCES stays (stay_id);
ALTER TABLE invoices ADD CONSTRAINT invoices_type_c
  CHECK ( invoice_type IN ('BOLETA','FACTURA') );
ALTER TABLE invoices ADD CONSTRAINT invoices_method_c
  CHECK ( payment_method IN ('CASH','DEBIT_CARD','CREDIT_CARD','YAPE','BANK_TRANSFER') );

rem ********************************************************************
rem Create indexes on foreign key columns
rem (columns already covered by a PK/UNIQUE index are not repeated;
rem  guests.last_name and reservations.channel are intentionally NOT indexed)

Prompt ******  Creating indexes ...

CREATE INDEX rooms_room_type_id_i          ON rooms           ( room_type_id );
CREATE INDEX employees_hotel_id_i          ON employees       ( hotel_id );
CREATE INDEX employees_manager_id_i        ON employees       ( manager_id );
CREATE INDEX reservations_guest_id_i       ON reservations    ( guest_id );
CREATE INDEX reservations_room_id_i        ON reservations    ( room_id );
CREATE INDEX reservations_employee_id_i    ON reservations    ( employee_id );
CREATE INDEX service_charges_stay_id_i     ON service_charges ( stay_id );
CREATE INDEX service_charges_service_id_i  ON service_charges ( service_id );

rem ********************************************************************
rem Create views

Prompt ******  Creating views ....

CREATE OR REPLACE VIEW hotel_revenue_summary AS
  SELECT CASE
           GROUPING_ID ( h.hotel_name, rt.type_name )
           WHEN 1 THEN 'HOTEL TOTAL'
           WHEN 2 THEN 'ROOM TYPE TOTAL'
           WHEN 3 THEN 'GRAND TOTAL'
         END total,
         h.hotel_name,
         rt.type_name,
         COUNT ( i.invoice_id ) invoice_count,
         SUM ( i.total_amount ) total_revenue
  FROM   invoices i
  JOIN   stays s         ON s.stay_id = i.stay_id
  JOIN   reservations r  ON r.reservation_id = s.reservation_id
  JOIN   rooms ro        ON ro.room_id = r.room_id
  JOIN   room_types rt   ON rt.room_type_id = ro.room_type_id
  JOIN   hotels h        ON h.hotel_id = ro.hotel_id
  GROUP  BY GROUPING SETS (
    ( h.hotel_name ),
    ( h.hotel_name, rt.type_name ),
    ( rt.type_name ),
    ()
  );

CREATE OR REPLACE VIEW service_sales_summary AS
  SELECT sv.category,
         sv.service_name,
         COUNT ( sc.charge_id ) times_sold,
         SUM ( sc.quantity * sc.unit_price ) total_sales
  FROM   services sv
  LEFT   JOIN service_charges sc ON sc.service_id = sv.service_id
  GROUP  BY sv.category, sv.service_name;

CREATE OR REPLACE VIEW employee_hierarchy AS
  SELECT employee_id, full_name, job_title, manager_id,
         LEVEL emp_level,
         LPAD ( ' ', 2 * ( LEVEL - 1 ) ) || full_name org_chart,
         SYS_CONNECT_BY_PATH ( full_name, ' > ' ) reporting_path
  FROM   employees
  START WITH manager_id IS NULL
  CONNECT BY PRIOR employee_id = manager_id;

rem ********************************************************************
rem Add table and column comments

Prompt ******  Adding table column comments ...

COMMENT ON TABLE hotels IS 'Hotels of the chain, located in different Peruvian cities';
COMMENT ON TABLE room_types IS 'Room categories with their capacity and reference rate';
COMMENT ON TABLE rooms IS 'Rooms of each hotel and their current nightly rate';
COMMENT ON TABLE guests IS 'People who book or stay at the hotels (Peruvian and foreign)';
COMMENT ON TABLE employees IS 'Staff members, including the reporting hierarchy via manager_id';
COMMENT ON TABLE reservations IS 'Room bookings: who, which room, dates, channel and status';
COMMENT ON TABLE stays IS 'Actual check-in / check-out of reservations that were used';
COMMENT ON TABLE services IS 'Extra services offered to guests (restaurant, spa, tours, etc.)';
COMMENT ON TABLE service_charges IS 'Extra services consumed during each stay';
COMMENT ON TABLE invoices IS 'Invoice (boleta / factura) issued at the end of each stay';

COMMENT ON COLUMN guests.document_type IS 'Valid values: DNI, PASSPORT, CE (carne de extranjeria)';
COMMENT ON COLUMN employees.manager_id IS 'Self-referencing FK to employees.employee_id; NULL for the top of the hierarchy';
COMMENT ON COLUMN reservations.employee_id IS 'Employee who registered the booking; NULL for web bookings';
COMMENT ON COLUMN reservations.channel IS 'Valid values: WEB, PHONE, AGENCY';
COMMENT ON COLUMN reservations.status IS 'Valid values: CONFIRMED, CHECKED_OUT, CANCELLED, NO_SHOW';
COMMENT ON COLUMN rooms.nightly_rate IS 'Price per night in soles (PEN)';
COMMENT ON COLUMN invoices.tax_amount IS 'IGV (18%) applied to room and services amounts';
COMMENT ON COLUMN invoices.total_amount IS 'room_amount + services_amount + tax_amount, in soles (PEN)';
